apiVersion: v1
appVersion: 2.41.0.1
name: activemq-artemis
description: |
  A Helm chart installing Apache ActiveMQ Artemis, 
  [forked](https://github.com/sherwin-williams-co/activemq-artemis-helm) from Device Insight GmbH
version: 1.10.1
icon: https://raw.githubusercontent.com/apache/activemq-artemis/2.9.0/artemis-website/src/main/resources/images/artemis-logo.png
maintainers:
  - name: Device Insight GmbH
  - name: Chad Lauritsen
    email: Chad.S.Lauritsen@sherwin.com
