apiVersion: v1
appVersion: latest-alpine
name: artemis
description: A Helm chart installing Apache ActiveMQ Artemis
version: 0.8.0
icon: https://raw.githubusercontent.com/apache/activemq-artemis/2.9.0/artemis-website/src/main/resources/images/artemis-logo.png
maintainers:
  - name: Device Insight GmbH
  - name: Chad.S.Lauritsen@sherwin.com
