{{- $fullname := include "artemis.fullname" . -}}
{{- $chartVersion := .Chart.Version -}}
{{- $fixedAfter := "1.11.0" -}}
{{- if and (eq $chartVersion $fixedAfter) (not (hasKey .Values "skipDeleteSts")) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{$fullname}}-hook-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{$fullname}}-hook-role
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{$fullname}}-hook-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
subjects:
  - kind: ServiceAccount
    name: {{$fullname}}-hook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{$fullname}}-hook-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: maybe-delete-{{$fullname}}-sts
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
spec:
  template:
    spec:
      serviceAccountName: {{$fullname}}-hook-sa
      containers:
        - name: check-and-delete
          image: bitnami/kubectl:latest
          command:
            - /usr/bin/bash
            - -c
            - |
              set -e
              version=$(kubectl get statefulset {{ $fullname }} \
                -n {{ .Release.Namespace }} \
                -o jsonpath="{.spec.template.metadata.labels.helm\.sh/chart}" \
                | awk -F- '{print $NF}'\
              )
              echo "Currently installed chart version: $version"
              if [ "$(printf '%s\n' "$version" {{$fixedAfter | quote }} | sort -V | head -n1)" != {{$fixedAfter | quote }} ]; then
                echo "Existing Artemis Chart StatefulSets less than {{$fixedAfter}} have a problem that prevents Helm upgrades"
                echo "We will now delete it, and this chart will recreate it momentarily."
                if kubectl delete statefulset {{$fullname}} -n {{ .Release.Namespace }} 
                then
                  echo "StatefulSet {{$fullname}} deleted successfully."
                else
                  echo "Failed to delete StatefulSet {{$fullname}}, it may not exist or is already deleted."
                fi
              else
                echo "Version is {{$fixedAfter}} or higher, skipping delete of existing StatefulSet."
              fi
      restartPolicy: Never
  {{- end }}