apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-scripts
data:
  {{- $files := .Files.Glob "scripts/*.sh" }}
  {{- range $path, $file := $files }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}