{{- $fullname := include "artemis.fullname" . }}
{{- $shwCostCenter := (.Values.global).shwCostCenter | default "lb9937" }}
{{- if (.Values.ingress).enabled }}
  {{- if false }}
---
# Middleware to enable WebSocket support in Traefik
#apiVersion: traefik.io/v1alpha1
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullname }}-websocket
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      Connection: "Upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      Access-Control-Allow-Origin: "*"
      {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  {{- with (.Values.ingress).tls }}
  tls:
    - hosts:
        - {{$fullname}}.{{$shwCostCenter}}-ingress.stores.sherwin.com
      secretName: {{ .secretName | default $fullname }}
  {{- end }}
  rules:
    - host: {{$fullname}}.{{$shwCostCenter}}-ingress.stores.sherwin.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{$fullname}}
                port:
                  number: 8161
{{- end }}