kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "artemis.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "artemis.fullname" . }}-tokenreview
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amq
{{/*rules:*/}}
{{/*  - apiGroups: ["authentication.k8s.io"]*/}}
{{/*    resources: ["tokenreviews"]*/}}
{{/*    verbs: ["create"]*/}}
---
# templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "artemis.fullname" . }}-secret-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
---
# templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "artemis.fullname" . }}-secret-manager-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "artemis.fullname" . }}-secret-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "artemis.fullname" . }}
    namespace: {{ .Release.Namespace }}