apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "artemis.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "artemis.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "artemis.fullname" . }}-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "artemis.fullname" . }}-tokenreview
subjects:
  - kind: ServiceAccount
    name: {{ include "artemis.fullname" . }}
    namespace: {{ .Release.Namespace }}
