{{- if not (.Values.auth).existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
stringData:
  clientPassword: >-
    {{ randAscii 21 | b64enc }}
  clusterPassword: >-
    {{ randAscii 21 | b64enc }}
{{- end }}
