{{ $fullname := include "artemis.fullname" . }}
{{- with .Values.appRoleSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-approle
stringData:
  {{- if .roleId }}
  VAULT_ROLE_ID: {{ .roleId }}
  {{- end }}
  {{- if .secretId }}
  VAULT_SECRET_ID: {{ .secretId }}
  {{- end }}
{{- end }}