---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "artemis.labels.live" . | nindent 6 }}
  serviceName: {{ include "artemis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        {{- include "artemis.psa" . | nindent 8 }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
        {{- end }}
      labels:
        {{- include "artemis.labels.live" . | nindent 8 }}
    spec:
      {{- include "artemis.statefulset.spec" . | nindent 6 }}
  {{- include "artemis.statefulset.volumeclaim" . | nindent 2 }}
